set -g base-index 1
setw -g pane-base-index 1
set -g mouse on
set -s set-clipboard on
set -g allow-passthrough on

# Window navigation
bind h previous-window
bind l next-window

set -g status-right ""

# leader+r refreshes pane
bind-key r respawn-pane -k

